# Numpy Array

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
arr.shape

(3,)

In [6]:
type(arr)

numpy.ndarray

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_mat = np.array(my_mat)

In [10]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
my_mat.shape

(3, 3)

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)
#Returns a 1d vector

array([0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#linspace returns an equal distribution compared to arange, returns a 1d vector
np.linspace(1,20,50)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.42254158, 0.77543254, 0.66337615, 0.69230638, 0.84364412])

In [20]:
np.random.rand(5,5)

array([[0.83808363, 0.83502894, 0.30279673, 0.81149451, 0.24122814],
       [0.67965898, 0.38307574, 0.57529822, 0.35006537, 0.15690244],
       [0.49236514, 0.23350808, 0.47392261, 0.50801602, 0.7428526 ],
       [0.75551819, 0.18941806, 0.80772088, 0.03854919, 0.91408687],
       [0.90523422, 0.92339865, 0.94732451, 0.954165  , 0.82917398]])

In [21]:
(np.random.rand(5,5)).shape

(5, 5)

In [22]:
np.random.randn(7) #Numbers based on normal distribution

array([-1.86923134,  0.44076526,  1.61609927, -1.90981671,  0.87509625,
       -0.57766083,  0.72777145])

In [23]:
np.random.randint(1,101,10)

array([ 4, 71, 34, 78, 84, 65,  5, 70,  9,  8])

In [24]:
np.random.randint(1,101,10).reshape(2,5)

array([[33, 28, 55, 18, 24],
       [18, 51, 78, 51, 96]])

In [25]:
np.random.randint(1,101,10).reshape(5,2)

array([[77,  1],
       [36, 49],
       [26, 62],
       [77, 40],
       [27, 37]])

In [27]:
arr = np.random.randint(0, 20 ,8)

In [28]:
arr

array([ 2,  1, 18,  0,  7, 17, 10,  8])

In [29]:
arr.max()

18

In [30]:
arr.min()

0

In [31]:
arr.argmax()

2

In [32]:
arr.argmin()

3

In [33]:
arr.shape

(8,)

In [35]:
arr.dtype

dtype('int32')